In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Load data

In [ ]:
#############################################################
#         TODO: read dataset as pandas dataframe            #
#############################################################

df = pd.read_excel('titanic.xls')


In [ ]:
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [ ]:
df.shape

(1309, 14)

In [ ]:
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [ ]:
#############################################################
#            TODO: Convert the dataset to X,y               #
#############################################################

# Split the dataframe into features (X) and target (y)
X = df.drop('survived', axis=1)  # Drop the 'survived' column to get the features
y = df['survived']  # Get the 'survived' column as the target variable

In [ ]:
X.isna().sum()

pclass          0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

## Preprocessing

In [ ]:
########################################################################
#     TODO: Delete columns that are not used or have too many nulls    #
########################################################################
# Define a list of columns to drop
drop_cols = ['name', 'ticket', 'cabin', 'boat', 'body', 'home.dest']

# Drop the columns from the dataframe
X = X.drop(drop_cols, axis=1)

In [ ]:
X.head()

pclass     sex      age  sibsp  parch      fare embarked
0       1  female  29.0000      0      0  211.3375        S
1       1    male   0.9167      1      2  151.5500        S
2       1  female   2.0000      1      2  151.5500        S
3       1    male  30.0000      1      2  151.5500        S
4       1  female  25.0000      1      2  151.5500        S

In [ ]:
X.nunique()

pclass        3
sex           2
age          98
sibsp         7
parch         8
fare        281
embarked      3
dtype: int64

In [ ]:
X.isna().sum()

pclass        0
sex           0
age         263
sibsp         0
parch         0
fare          1
embarked      2
dtype: int64

In [ ]:
############################################################################################
#     TODO: Fill in the nulls with the appropriate value, such as median, mean or mode     #
############################################################################################
# Calculate median age
median_age = X['age'].median()

# Fill in null values for 'age' column with median age
X['age'].fillna(median_age, inplace=True)

# Calculate median fare
median_fare = X['fare'].median()

# Fill in null values for 'fare' column with median fare
X['fare'].fillna(median_fare, inplace=True)

# Calculate mode for 'embarked' column
mode_embarked = X['embarked'].mode()[0]

# Fill in null values for 'embarked' column with mode
X['embarked'].fillna(mode_embarked, inplace=True)

In [ ]:
# All columns must not contain null

X.isna().sum()

pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [ ]:
X.nunique()

pclass        3
sex           2
age          98
sibsp         7
parch         8
fare        281
embarked      3
dtype: int64

In [ ]:
#############################################################
#    TODO: create Dummy Variable for categorical columns    #
#############################################################
# Create dummy variables for 'sex' column
X['is_male'] = pd.get_dummies(X['sex'], drop_first=True)

# Create dummy variables for 'embarked' column
X = pd.concat([X, pd.get_dummies(X['embarked'], prefix='embarked', drop_first=True)], axis=1)

# Drop the original categorical columns
X = X.drop(['sex', 'embarked'], axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [ ]:
#############################################################
#              TODO: Normalize numeric columns              #
#############################################################

from sklearn.preprocessing import StandardScaler

# Define the columns to normalize
cols_to_normalize = ['age', 'sibsp', 'parch', 'fare']

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the selected columns
scaler.fit(X[cols_to_normalize])

# Transform the selected columns using the scaler
X[cols_to_normalize] = scaler.transform(X[cols_to_normalize])

In [ ]:
from sklearn.decomposition import PCA

##############################################################
#  TODO: Reduce input dimensions to 5 dimensions using PCA   #
##############################################################

# Define the number of dimensions to reduce to
n_components = 5

# Create a PCA object
pca = PCA(n_components=n_components)

# Fit and transform the data using PCA
X_pca = pca.fit_transform(X)

# Create a new dataframe with the reduced dimensions
X_pca_df = pd.DataFrame(data=X_pca, columns=[f"PC{i}" for i in range(1, n_components+1)])

In [ ]:
#############################################################
#              TODO: split to train and test                #
#############################################################

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_pca_df, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(1047, 5)

In [ ]:
X_test.shape

(262, 5)

## Desisiom Tree

In [ ]:
from sklearn import tree
###################################################################
#  TODO: Train the decision tree classifier on the training data  #
###################################################################

# Create a decision tree classifier object
clftree = tree.DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
clftree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict the output class for the training data
y_train_pred = clftree.predict(X_train)

# Predict the output class for the test data
y_test_pred = clftree.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.9703915950334289
Testing accuracy: 0.6946564885496184
Testing precision: 0.6938775510204082
Testing recall: 0.576271186440678
Testing F1 score: 0.6296296296296295
Testing confusion matrix:
[[114  30]
 [ 50  68]]


## Bagging

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html

In [ ]:
from sklearn.ensemble import BaggingClassifier
###################################################################
#      TODO: Train the bagging classifier on the training data    #
###################################################################

# Create a bagging classifier object
bag_clf = BaggingClassifier(base_estimator=clftree, n_estimators=100, random_state=42)

# Train the classifier on the training data
bag_clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(random_state=42),
                  n_estimators=100, random_state=42)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict the output class for the training data
y_train_pred = bag_clf.predict(X_train)

# Predict the output class for the test data
y_test_pred = bag_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.9703915950334289
Testing accuracy: 0.7099236641221374
Testing precision: 0.7058823529411765
Testing recall: 0.6101694915254238
Testing F1 score: 0.6545454545454547
Testing confusion matrix:
[[114  30]
 [ 46  72]]


## Random Forest

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor

In [ ]:
from sklearn.ensemble import RandomForestClassifier
###################################################################
#  TODO: Train the Random Forest classifier on the training data  #
###################################################################

# Create a Random Forest classifier object
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict the output class for the training data
y_train_pred = rf_clf.predict(X_train)

# Predict the output class for the test data
y_test_pred = rf_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.9703915950334289
Testing accuracy: 0.7213740458015268
Testing precision: 0.7142857142857143
Testing recall: 0.635593220338983
Testing F1 score: 0.6726457399103138
Testing confusion matrix:
[[114  30]
 [ 43  75]]


### Grid Search for Random Forest

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [ ]:
from sklearn.model_selection import GridSearchCV

#################################################################################################################################################
# TODO: Find the best available parameters (2 parameters for search) for Random Forest classifier using grid search and do the training with it #
#################################################################################################################################################

# Create a Random Forest classifier object
rfc = RandomForestClassifier(random_state=42)

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 10]
}

# Create a grid search object
grid_search = GridSearchCV(rfc, param_grid=param_grid, cv=5, n_jobs=-1)

# Perform the grid search on the training data
grid_search.fit(X_train, y_train)

# Print the best parameters and the corresponding score
print("Best parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

# Train a new Random Forest classifier with the best hyperparameters
rfc_best = RandomForestClassifier(n_estimators=grid_search.best_params_['n_estimators'], 
                                   max_depth=grid_search.best_params_['max_depth'], 
                                   random_state=42)
rfc_best.fit(X_train, y_train)

Best parameters: {'max_depth': 5, 'n_estimators': 200}
Best score: 0.740209614946457


RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict the output class for the training data
y_train_pred = rfc_best.predict(X_train)

# Predict the output class for the test data
y_test_pred = rfc_best.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.7936962750716332
Testing accuracy: 0.7022900763358778
Testing precision: 0.803030303030303
Testing recall: 0.4491525423728814
Testing F1 score: 0.5760869565217392
Testing confusion matrix:
[[131  13]
 [ 65  53]]


## Gradient Boosting

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
###################################################################
# TODO: Train the Gradient Boost classifier on the training data  #
###################################################################

# Create a gradient boosting classifier object
gb_clf = GradientBoostingClassifier()

# Fit the model to the training data
gb_clf.fit(X_train, y_train)

GradientBoostingClassifier()

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict output class for the training data
y_train_pred = gb_clf.predict(X_train)

# Predict output class for the test data
y_test_pred = gb_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.8767908309455588
Testing accuracy: 0.7366412213740458
Testing precision: 0.7752808988764045
Testing recall: 0.5847457627118644
Testing F1 score: 0.6666666666666666
Testing confusion matrix:
[[124  20]
 [ 49  69]]


## Ada Boost

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
###################################################################
#    TODO: Train the Ada Boost classifier on the training data    #
###################################################################

# Create an instance of the AdaBoostClassifier
ada_clf = AdaBoostClassifier()

# Fit the model to the training data
ada_clf.fit(X_train, y_train)

AdaBoostClassifier()

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict output class for the training data
y_train_pred = ada_clf.predict(X_train)

# Predict output class for the test data
y_test_pred = ada_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.7564469914040115
Testing accuracy: 0.6793893129770993
Testing precision: 0.7361111111111112
Testing recall: 0.4491525423728814
Testing F1 score: 0.5578947368421052
Testing confusion matrix:
[[125  19]
 [ 65  53]]


## XG Boost

http://xgboost.readthedocs.io/en/latest/

In [ ]:
import xgboost as xgb
###################################################################
#    TODO: Train the XG boost classifier on the training data     #
###################################################################

# Create an instance of the XGBoost Classifier
xgb_clf = xgb.XGBClassifier()

# Fit the model to the training data
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict output class for the training data
y_train_pred = xgb_clf.predict(X_train)

# Predict output class for the test data
y_test_pred = xgb_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.9656160458452722
Testing accuracy: 0.732824427480916
Testing precision: 0.7307692307692307
Testing recall: 0.6440677966101694
Testing F1 score: 0.6846846846846847
Testing confusion matrix:
[[116  28]
 [ 42  76]]


### Grid Search for XGBoost

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [ ]:
from sklearn.model_selection import GridSearchCV

###########################################################################################################################################
# TODO: Find the best available parameters (4 parameters for search) for XGboost classifier using grid search and do the training with it #
###########################################################################################################################################

# Create an instance of the XGBoost Classifier
xgb_clf = xgb.XGBClassifier()

# Define the hyperparameters to search over using a dictionary
param_grid = {
    'learning_rate': [0.01, 0.1, 0.3, 0.5],
    'max_depth': [3, 5, 6, 7],
    'n_estimators': [50, 100, 150],
    'subsample': [0.5, 0.75, 1.0]
}

# Create an instance of the GridSearchCV with the XGBoost Classifier and the hyperparameters to search over
grid_search = GridSearchCV(estimator=xgb_clf, param_grid=param_grid, cv=5)

# Fit the GridSearchCV to the training data
grid_search.fit(X_train, y_train)

# Print the best hyperparameters found by the grid search
print("Best hyperparameters: ", grid_search.best_params_)

# Train the XGBoost Classifier with the best hyperparameters found by the grid search
xgb_clf_best = xgb.XGBClassifier(**grid_search.best_params_)
xgb_clf_best.fit(X_train, y_train)

Best hyperparameters:  {'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 50, 'subsample': 0.5}


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=50, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

# Predict output class for the training data
y_train_pred = xgb_clf_best.predict(X_train)

# Predict output class for the test data
y_test_pred = xgb_clf_best.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################

# Calculate accuracy for the training data
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate metrics for the test data
test_acc = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.8099331423113658
Testing accuracy: 0.732824427480916
Testing precision: 0.7790697674418605
Testing recall: 0.5677966101694916
Testing F1 score: 0.6568627450980393
Testing confusion matrix:
[[125  19]
 [ 51  67]]
